# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_groupwaitinginforamtion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_group_information(object):
    def setupUi(self, Form_group_information):
        Form_group_information.setObjectName("Form_group_information")
        Form_group_information.resize(539, 481)
        Form_group_information.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(Form_group_information)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form_group_information)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_group = QtWidgets.QLabel(Form_group_information)
        self.label_group.setObjectName("label_group")
        self.horizontalLayout.addWidget(self.label_group)
        self.label_queue_information = QtWidgets.QLabel(Form_group_information)
        self.label_queue_information.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_queue_information.setObjectName("label_queue_information")
        self.horizontalLayout.addWidget(self.label_queue_information)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_calling_patient_information = QtWidgets.QLabel(Form_group_information)
        self.label_calling_patient_information.setObjectName("label_calling_patient_information")
        self.verticalLayout.addWidget(self.label_calling_patient_information)
        self.tabWidget = QtWidgets.QTabWidget(Form_group_information)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_waiting_patient_informatio = QtWidgets.QWidget()
        self.tab_waiting_patient_informatio.setObjectName("tab_waiting_patient_informatio")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_waiting_patient_informatio)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_group_waiting_information = QtWidgets.QTableWidget(self.tab_waiting_patient_informatio)
        self.tableWidget_group_waiting_information.setMinimumSize(QtCore.QSize(256, 192))
        self.tableWidget_group_waiting_information.setMaximumSize(QtCore.QSize(10000, 10000))
        self.tableWidget_group_waiting_information.setObjectName("tableWidget_group_waiting_information")
        self.tableWidget_group_waiting_information.setColumnCount(0)
        self.tableWidget_group_waiting_information.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_group_waiting_information, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_waiting_patient_informatio, "")
        self.tab_order_patient_informatio = QtWidgets.QWidget()
        self.tab_order_patient_informatio.setObjectName("tab_order_patient_informatio")
        self.tabWidget.addTab(self.tab_order_patient_informatio, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form_group_information)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_group_information)

    def retranslateUi(self, Form_group_information):
        _translate = QtCore.QCoreApplication.translate
        Form_group_information.setWindowTitle(_translate("Form_group_information", "Form"))
        self.label.setText(_translate("Form_group_information", "科室："))
        self.label_group.setText(_translate("Form_group_information", "普通内科"))
        self.label_queue_information.setText(_translate("Form_group_information", "TextLabel"))
        self.label_calling_patient_information.setText(_translate("Form_group_information", "当前呼叫病人信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_waiting_patient_informatio), _translate("Form_group_information", "等候病人列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_order_patient_informatio), _translate("Form_group_information", "预约病人信息"))
