# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_display_dismode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_display_dismode(object):
    def setupUi(self, Form_display_dismode):
        Form_display_dismode.setObjectName("Form_display_dismode")
        Form_display_dismode.resize(292, 51)
        self.gridLayout = QtWidgets.QGridLayout(Form_display_dismode)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_display_No = QtWidgets.QCheckBox(Form_display_dismode)
        self.checkBox_display_No.setObjectName("checkBox_display_No")
        self.horizontalLayout.addWidget(self.checkBox_display_No)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Form_display_dismode)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_dismode = QtWidgets.QComboBox(Form_display_dismode)
        self.comboBox_dismode.setObjectName("comboBox_dismode")
        self.horizontalLayout.addWidget(self.comboBox_dismode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(4, 3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form_display_dismode)
        QtCore.QMetaObject.connectSlotsByName(Form_display_dismode)

    def retranslateUi(self, Form_display_dismode):
        _translate = QtCore.QCoreApplication.translate
        Form_display_dismode.setWindowTitle(_translate("Form_display_dismode", "Form"))
        self.checkBox_display_No.setText(_translate("Form_display_dismode", "N号屏"))
        self.label.setText(_translate("Form_display_dismode", "显示模式："))
